### ISSUE TITLE
Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "chang1.png" this most likely mean s the gm/convert binaries can't be found

### ISSUE THREAD

**Issue by TonyGao625** [bamlab/generator-rn-toolbox#109]
Why is this happening? I have installed ImageMagick for windows.

Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "chang1.png" this most likely mean
s the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\generator-rn-toolbox\node_modules\gm\lib\
command.js:232:12)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at ChildProcess.cp.emit (C:\Users\admin\AppData\Roaming\npm\node_modules\generator-rn-toolbox\node_modules\cross-spawn
\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

I also try  convert --version . It displays like this......

PS F:\ReactNativeProject\MyApp> convert --version
Invalid drive specification.

**Comment by Almouro** [comment]
Hi @TonyGao625, 
Thanks for posting an issue here!

I see that you're on Windows, can you try to reinstall image magick with the legacy tools, to see if it works?
You can see how to do it [here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/README.md#troubleshooting).

**Comment by Almouro** [comment]
Hi @TonyGao625, do you still have an issue with the generator, or did that fix your problem?

**Comment by jbarradas** [comment]
@Almouro I did it and worked for me ;)

Then had another problem, but I'll open a new Issue for it.

Thanks

**Comment by Almouro** [comment]
Ok thanks! closing this one then :)

**Comment by joebjoe** [comment]
@Almouro having this same issue (already reinstalled with legacy as suggested above).

**Comment by jeanru** [comment]
I have same issue too after installed gm and imagemagick.
err: Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "/var/folders/nv/1m164hpn5038mj9t4s4vfjgc0000gn/T/upload_2d1b64f289c31203f77b63e8ff1154bd" this most likely means the gm/convert binaries can't be found

**Comment by joebjoe** [comment]
@jeanru I meant to come back here and update - but I solved mine by running cmd.exe as an administrator.

Basically the executable is unable to find/communicate with ImageMagick/Graphicksmagick, so as long as one of the two are installed locally, then something else is hindering communication. It could be a permissions issue - thus running the command line as an administrator. Hope it's the same for you.

**Comment by tharunShiv** [comment]
Yes, @joebjoe  has the right solution. **Open the command promt or the gitbash as Administrator**. It works. Thanks

**Comment by KayhanB** [comment]
I have tried run command promt as admin but not working same issue.

**Comment by Venegrad** [comment]
same issue, windows app not working
