### ISSUE TITLE
when generating android splash screen, files with -0, -1, -2, -3 suffixes are being created.

### ISSUE THREAD

**Issue by foysalit** [bamlab/generator-rn-toolbox#110]
This is the command I'm running - `yo rn-toolbox:assets --splash ~/Downloads/chrome/Splash\ Screen --android` and it finishes successfully and does generate the splash screens. However, looks like in each folder, it's creating 4 files - 
`launch_screen-0.png` 
`launch_screen-1.png` 
`launch_screen-2.png` 
`launch_screen-3.png`
even though the output says - 
`Wrote android/app/src/main/res/drawable-land-ldpi/launch_screen.png`

It would still be okay but looks like android does not allow the character `-` in the resource filenames so when trying to run my app, I'm getting the following error message - 
`Error: '-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore`

I have looked into the code and it looks like the number suffixed files are supposed to be generated for ios icons so I'm guessing it's somehow leaking from there and making it's way into splash screen generation? I would love to make a PR if you could point me to the right direction about fixing it.

**Comment by Almouro** [comment]
Hi @foysalit ,

Thanks for posting the issue here!
The splashscreen generation code is [here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/imageGenerator.js#L152) so it's quite strange that it's adding suffixes...

My best hypothesis is that your file is actually a `psd` file and the generator is creating one splash screen for each layer.

**Comment by foysalit** [comment]
You're right, my file is actually `.psd`. 
I did find the piece of the code that generates the files and looks like for psd files it adds a ```[0]``` which I think is supposed to specify the top layer only? here's the line I'm talking about - `https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/assets/imageGenerator.js#L110`
but that's as far as I could dig. any clue how to fix this?

**Comment by yleflour** [comment]
Is it possible to flatten the image instead of selecting the top layer? It seems more optimal regarding traditional Photoshop usage.

**Comment by Almouro** [comment]
Hmm not sure, @foysalit can you share the image you were trying to use?

Converting the image to png should work though.
