### ISSUE TITLE
Missing App Store icon (1024pt)

### ISSUE THREAD

**Issue by tmaly1980** [bamlab/generator-rn-toolbox#123]
This works great but it looks like (possibly due to iTunes/XCode updates) it misses generating the 1024pt App Store icon. It appears to be blank in Images.xcassets and iTunesConnect refuses to publish to TestFlight because of the lack of an icon. Maybe it was never this toolkit's intention to generate that specific icon but I think it would be good to do so.

**Comment by Almouro** [comment]
Hi @tmaly1980 , 
Thanks for reporting this. Indeed this is new in XCode 9, and #122 already took care of it, thanks to @Minishlink but was not published.

We have automatic publishing setup but we need to follow certain commit messages convention. I added a few info info in #124 and also added an update trigger in the PR.

**Comment by trevorackerman** [comment]
This is something I need for a project too. When will it be released?

**Comment by Almouro** [comment]
Sorry, the PR had been squashed so the automatic publishing did not work haha.
It is now published as `2.4.0`.

@tmaly1980 I'm closing then, but please reopen if your issue isn't fixed! :)
