### ISSUE TITLE
Getting the following error, seems to be an issue with image generator 

### ISSUE THREAD

**Issue by AlmogRnD** [bamlab/generator-rn-toolbox#128]
Error 1: ITMS-90096 - Your binary is not optimized for iPhone 5
Your binary is not optimized for iPhone 5 - New iPhone apps and app updates submitted must support the 4-inch display on iPhone 5 and must include a launch image referenced in the Info.plist under UILaunchImages with a UILaunchImageSize value set to {320, 568}. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the 'iOS Human Interface Guidelines' at https://developer.apple.com/ios/human-interface-guidelines/graphics/launch-screen.

**Comment by Almouro** [comment]
Hi @AlmogRnD, thanks for posting this issue!

What is your configuration, especially, what is your XCode version?

We recently updated for XCode 9. Not sure if everything still works with XCode 8, @Minishlink do you know? :)

**Comment by Minishlink** [comment]
Not sure why it would impact archiving with XCode 8, but you can try upgrading to XCode 9!

What are your `Info.plist`, `AppIcon.appiconset/Contents.json`, and `LaunchScreen.xib`?

**Comment by AlmogRnD** [comment]
@Minishlink I'm on xcode 9 I ended adding my icons manually

**Comment by Almouro** [comment]
@AlmogRnD ok wrong guess on my side then :)
Is it possible for you to share your icon and the command you ran?

**Comment by yleflour** [comment]
Fixed in #138
