### ISSUE TITLE
Getting the following error - Error 2: ITMS-90022 - Missing required icon file

### ISSUE THREAD

**Issue by AlmogRnD** [bamlab/generator-rn-toolbox#129]
Error 2: ITMS-90022 - Missing required icon file
Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0.

**Comment by Almouro** [comment]
Same comment as #128

**Comment by yleflour** [comment]
Closing duplicate
