### ISSUE TITLE
Android splash screen is not full screen?

### ISSUE THREAD

**Issue by danieldelouya** [bamlab/generator-rn-toolbox#133]
The splash screen (launchimage) is not full screen on Android. About 50 pixel space on each side. How can i fix that?

**Comment by danieldelouya** [comment]
Never mind. Changed the gravity. New to Android lol.

**Comment by djalmaaraujo** [comment]
@danieldelouya How you fixed this?

**Comment by uppercase-army** [comment]
@danieldelouya you can change the gravity in the xml file inside the drawable folder e.g. launch_screen_bitmap.xml:

```

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
  <item android:drawable="@color/splashBackground"/>
  <item>
    <bitmap
      android:src="@drawable/launch_screen"
      android:gravity="center"/>
  </item>
</layer-list>

```

You will see the default value is **center** which can be changed to:

fill_horizontal|fill_vertical
fill

See possible values here:

https://developer.android.com/reference/android/R.attr.html#gravity

Unfortunately it stretches the splash image I used. Hopefully yours looks better.

Rob
