### ISSUE TITLE
Async tasks while Splashscreen is showing?

### ISSUE THREAD

**Issue by rizwanahmed19** [bamlab/generator-rn-toolbox#136]
How to do something async while splashscreen is showing?

**Comment by philolo1** [comment]
@rizwanahmed19 i would recommend you to use react-native-splash-screen and you show the splashscreen as long as you want and then call hide.

**Comment by yleflour** [comment]
+1 to @philolo1 's answer. [Link for the lazy](https://github.com/crazycodeboy/react-native-splash-screen) and closing thread.
