### ISSUE TITLE
app rename is not working if name contains UTF-8 character

### ISSUE THREAD

**Issue by emreesirik** [bamlab/generator-rn-toolbox#140]
Hi, I want to rename my react app with generator-rn-toolbox but when I try to give a name like "Güçlü", it gives an error. Is there any restriction about UTF-8 character

**Comment by yleflour** [comment]
Can you give us which command you launched and which answers you put in (as long as it's not confidential)?

**Comment by Almouro** [comment]
Hi @emreesirik , was your issue solved?
I'm closing this, since there hasn't been any activity for a while, but feel free to reopen if your problem wasn't fixed :)
