### ISSUE TITLE
Splash Screen "Please use a square image" 

### ISSUE THREAD

**Issue by ranvirgorai** [bamlab/generator-rn-toolbox#148]
Square image as splash screen can cause cropping issue

**Comment by Almouro** [comment]
Hi @ranvirgorai, 
Thanks for posting an issue here!

Can you tell us the command you ran, and if possible a screenshot of the failed splash screen?

**Comment by ranvirgorai** [comment]
I am using a patriot image

`yo rn-toolbox:assets --splash ~/Desktop/background.png --android`

![screen shot 2017-11-27 at 5 53 05 pm](https://user-images.githubusercontent.com/5949243/33266520-fba2820e-d39b-11e7-8d53-d6f34303c489.png)

can I use patriot image instead of square?

**Comment by Almouro** [comment]
Sorry @ranvirgorai, I don't know what a patriot image is, can you explain?
For now only square images are supported, but PRs are welcome :)

**Comment by joh-klein** [comment]
Maybe he means an image in portrait format? :)

**Comment by ZitaNguyen** [comment]
I also have a problem with spashscreen. Cropping images after the command are not correct for portrait iPhoneX/Xs, iPhone 8+, iPhone 7+ Retina. There is no image for iPhone 5,6. All landscape images and iPad portrait images work well.

**Comment by abybaby123** [comment]
I faced the same while generating splash for my project for iOS. Is it expecting a 1024 X 1024 image as input? Please confirm

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version handles 3 different types of rendering for the splashscreen image (center, contain) and does not rely on a square image, so it should solve your issue 😉
