### ISSUE TITLE
Launch Screen for iPad Multitasking

### ISSUE THREAD

**Issue by flyingxu** [bamlab/generator-rn-toolbox#156]
I'm trying to use the `yo rn-toolbox:assets --splash ./img/Launch_2208x2208.png --ios` command but I get an error for iPad Multitasking: 

    ERROR ITMS-90475: "Invalid Bundle. iPad Multitasking support requires launch story board in bundle 'com.abc'."

I know I can disable iPad Multitasking by requiring full screen, but would it be nice that `generator-rn-toolbox` supports to make it as easy as a command line?

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

It produces a .xib instead of a "SplashImage" per Apple's requirements, so it should solve your issue 😉
