### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Alexintosh** [bamlab/generator-rn-toolbox#166]
After installing the generato it cannot be found from yo.

Error:
```
Error rn-toolbox:assets --icon ./icon.png

You don't seem to have a generator with the name rn-toolbox:assets installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 25 registered generators run yo with the `--help` option.
```

Platform:
Mac os X 10.12.6 (16G1114)
node v8.1.2

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)


The new version is a react-native CLI plugin and does not depend on yeoman, so it should solve your issue 😉
