### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by SirPhemmiey** [bamlab/generator-rn-toolbox#180]
Hi guys, 
I got some errors while trying to generate my icon. Here it is 
`events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "logo.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\generator-rn-toolbox\node_modules\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (C:\Users\PC\AppData\Roaming\npm\node_modules\generator-rn-toolbox\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`

**Comment by brkscosta** [comment]
I have the same problem, i try run my terminal as admintrator but its show the same error. My Node version is 10.0
![screenshot_1](https://user-images.githubusercontent.com/31209677/41133488-1b8ad93a-6abf-11e8-9d37-ba1c63aacbe7.jpg)

**Comment by yangy46** [comment]
If on Windows try reinstalling ImageMagick. Make sure to install the dll version (ie: ImageMagick-7.0.8-10-Q8-x64-dll.exe) and check the "install legacy utilities". The static .exe version doesn't seem to have this selection. See: https://github.com/bamlab/generator-rn-toolbox/tree/master/generators/assets#troubleshooting

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)


The new version does not depend on image magick, so it should solve your issue 😉
