### ISSUE TITLE
Rounded icons on Android

### ISSUE THREAD

**Issue by tommycarpi** [bamlab/generator-rn-toolbox#181]
Is it possible to have the icons for Android rounded, rather than squared?
I have no physical device to test it on, but on the Android Studio emulator I got all default apps rounded, and mine squared 👯 .

P.s. the icon I'm using is squared.

**Comment by roysG** [comment]
+1

**Comment by roysG** [comment]
for making square icon i just need to add the word to the filename and thats it?

**Comment by kenshinman** [comment]
Why not just make it rounded already in the design and export use png instead

**Comment by wregis** [comment]
I see little need for creating a new round image automatically, maybe a parameter that will output with a different filename (`--anddrod-round`) other that `ic_launcher.png` (e.g.: `ic_launcher_round.png`) or allow for a custom one (`--filename`).

**Comment by vdelacou** [comment]
#216  I just submit a pull request to automatically generate the ic_launcher_round.png

**Comment by guillermoroblesjr** [comment]
As a temporary work around you can use @vdelacou pull request which works great! 

`sudo npm install -g "git://github.com/bamlab/generator-rn-toolbox.git#d10da2de"`

**Comment by ThiagoAugustoSM** [comment]
I just used @guilhermebruzzi snippet and @vdelacou code to solve the problem. thanks guys

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)


The new version generates Android adaptive icons, so it should solve your issue 😉

**Comment by comp-phys-marc** [comment]
I can confirm that https://github.com/bamlab/generator-rn-toolbox/pull/216 works great. Hopefully it is merged soon!
