### ISSUE TITLE
splash screen size issue in android

### ISSUE THREAD

**Issue by imadarif** [bamlab/generator-rn-toolbox#187]
i prepare a splash.png file with 2732*2732. i run the command to generate splash screen for both ios and android. for ios is perfect but for android its showing color on background image was not fit properly

**Comment by bintoll** [comment]
+1 the same

**Comment by Juliocbr** [comment]
+1 the same

**Comment by joh-klein** [comment]
duplicate of #172 ?

**Comment by russ666** [comment]
found the solution: replace in `./android/app/src/main/res/drawable/launch_screen_bitmap.xml` value of `android:gravity` from `center` to `fill`

**Comment by airled** [comment]
@russ666 It fills, yes, but it resizes image incorrectly if display and image have different ratio

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version handles 3 different types of rendering for the splashscreen image (center, contain and cover), so it should solve your issue 😉
