### ISSUE TITLE
-bash: yo: command not found

### ISSUE THREAD

**Issue by kagmanoj25** [bamlab/generator-rn-toolbox#188]
I want to generate icon and splash automatically into my project. For this i have used following command in terminal.
1. yarn add global yo generator-rn-toolbox
2. brew install imagemagick
3. yo rn-toolbox:assets --icon <path to your icon>

when i'm trying to add icon (3rd point command) then i get the below error.
-bash: yo: command not found

Can anybody have good solution for this issue?

**Comment by fiznool** [comment]
Try using npm instead of yarn. I’ve had issues using yarn to install global packages before.

**Comment by schumannd** [comment]
You need to install Yeoman (npm install -g yo) to run Yeoman generators (see [this SO answer](https://stackoverflow.com/a/45675860/1175081))

This should definetely be mentioned in the README

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)


The new version is Yeoman free and uses the standard React-Native cli plugin architecture so it should solve your issue 😉
