### ISSUE TITLE
New Release when?

### ISSUE THREAD

**Issue by joh-klein** [bamlab/generator-rn-toolbox#193]
I desperately looking forward for a new release on npm, since there are a couple of fixes here that I really need :)
Any plans?

**Comment by Almouro** [comment]
Hi @joh-klein, thanks for reporting!
Yup, our auto publish was broken when all the NPM tokens were revoked following that nasty eslint-plugin-scope issue.
Anyway, new version was just released, and semantic-release should now automatically report failed publishing :)
