### ISSUE TITLE
Support for ic_launcher_round

### ISSUE THREAD

**Issue by iotashan** [bamlab/generator-rn-toolbox#197]
RN 0.57.0 adds a new icon to the default android project, ic_launcher_round.

![image](https://user-images.githubusercontent.com/420966/45171103-290b1300-b1c7-11e8-9882-713430055258.png)

![image](https://user-images.githubusercontent.com/420966/45171123-30322100-b1c7-11e8-9333-85d4b0c0fde6.png)

It would be great if rn-toolbox:assets was updated to support generating this image, too. It might need a separate source that the normal icon, given how much a circle cuts off.

**Comment by roysG** [comment]
Any update?

**Comment by vdelacou** [comment]
#216  Just submit a pull request

**Comment by schumannd** [comment]
Maybe the readme in `generator-rn-toolbox/generators/assets/README.md ` should also be updated as it currently suggests generating the android launcher icon through android studio

**Comment by c1ngular** [comment]
@schumannd  good point , though i found that icons generated by the android studio way , has better resolution , better picture quality on my test device .

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version generates Android adaptive icons, so it should solve your issue as long as the input image follows [adaptive icons guidelines](https://medium.com/google-design/designing-adaptive-icons-515af294c783)😉
