### ISSUE TITLE
create splashscreen based on icon 

### ISSUE THREAD

**Issue by sibelius** [bamlab/generator-rn-toolbox#198]
can we create a splash screen only based on an icon?

the idea is to center the icon and let the background to be white or other color

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version is offers 3 ways to handle splashscreen image positioning so it should solve your issue 😉
