### ISSUE TITLE
Support Android O adaptative icon

### ISSUE THREAD

**Issue by ammichael** [bamlab/generator-rn-toolbox#199]
Android O supports new formats of icons. Using the icons generated by rn-toolbox on Oreo is causing the icons to be adapted by the system, which results in the icon as seen below. Any chance updating the generator to create adaptive icons for Android??

By the way, thanks for this awesome generator 🤘

![screenshot_1538705948](https://user-images.githubusercontent.com/6873880/46512818-48c84200-c82c-11e8-9cc4-9813154cb602.png)

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version generates Android adaptive icons, so it should solve your issue 😉
