### ISSUE TITLE
Add support for non square images

### ISSUE THREAD

**Issue by fluffypomeranian** [bamlab/generator-rn-toolbox#202]
Steps to reproduce:

```
Mojo git:(bouncers-line) ✗ yo rn-toolbox:assets --icon src/images/mojo-cat.png
? Name of your react-native project Mojo
Please use a square image
➜  Mojo git:(bouncers-line) ✗
```

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version handles non-square images thanks to the switch to sharp for image processing. So it should solve your issue 😉
