### ISSUE TITLE
Yo throw new TypeError

### ISSUE THREAD

**Issue by muhammadridho** [bamlab/generator-rn-toolbox#218]
Hi, when i run `yo rn-toolbox:assets --icon`

i got this error,

```
/usr/local/lib/node_modules/yo/node_modules/conf/index.js:69
			throw new TypeError('Use `delete()` to clear values');
			^

TypeError: Use `delete()` to clear values
    at Conf.set (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:69:10)
    at Insight.set optOut [as optOut] (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:56:15)
```

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version is Yeoman free and uses the standard React-Native cli plugin architecture so it should solve your issue 😉
