### ISSUE TITLE
Icons are not created but no error?

### ISSUE THREAD

**Issue by itsallbr0ken** [bamlab/generator-rn-toolbox#227]
Running the following command

yo rn-toolbox:assets —icon icon.png

I get prompted for the project name which is correct and on either hitting enter or typing the project name and hitting enter, nothing happens, just a new terminal line and no icons?

```
Gareths-MacBook-Pro:unisongwent itsallbroken$ yo rn-toolbox:assets —icon icon.png
? Name of your react-native project UnisonGwent
Gareths-MacBook-Pro:unisongwent itsallbroken$ 
```

**Comment by civinski** [comment]
Same problem here...

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

It should solve your issue 😉
