### ISSUE TITLE
yo rn-toolbox icon and splash cant replace files

### ISSUE THREAD

**Issue by JurieSpies** [bamlab/generator-rn-toolbox#228]
all runs smooth but when it asks me to replace a file I cant type 'Y'. The screen just stays there no matter what I do. I have to quit my terminal to continue. Any advice, please?

**Comment by yleflour** [comment]
Hello, we just revamped the generator 😁

For up to date icon and splashscreen generation please use [@bam.tech/react-native-make](https://github.com/bamlab/react-native-make)

The new version is Yeoman free and uses the standard React-Native cli plugin architecture so it should solve your issue 😉
