### ISSUE TITLE
generator is not accessible after installing

### ISSUE THREAD

**Issue by jcollum** [bamlab/generator-rn-toolbox#33]
Your readme is a bit confusing. I haven't used Yo for a while but it's usually: 

1. Install generator
1. call yo with generator name
1. follow prompts

But the readme: 

    Retrieve all the generators with npm install -g yo generator-rn-toolbox

Retrieve all? What? 

    And then in a React Native project, use any above generator.

But... your generator is supposed to make a RN project, why would I use it from within a project? 

Ok that's just language issues I guess. But I can't get your generator to show in the list: 

```
$ yo 
? 'Allo CDK! What would you like to do? Install a generator
? Search npm for generators: rn-toolbox
? Here's what I found. Official generator → ෴
  Install one? rn-toolbox React-Native generators to kickstart your project
/Users/collumj/.nvm/versions/node/v6.9.1/lib
└── generator-rn-toolbox@1.0.0 

I just installed a generator by running:

    npm install -g generator-rn-toolbox

? 'Allo CDK! What would you like to do? 
  Coffee Fullstack 
  Karma 
  Angular Gulp Coffee 
❯ Lean Mean 
  React Seed 
  Material React 

```

That's the end of the list. Is yours not called RN-Toolbox (or something similar) after it's installed? I don't get it.

**Comment by Almouro** [comment]
Hi @jcollum, thanks for your feedback! 😄 
It's true that our README.md can be a bit confusing. 😕 

I submitted a PR ( #34 ) intending to improve the clarity, feel free to tell us if it's better!

Our generator does not setup a React Native project, but include many sub-generators to help you with some common tasks when working with one.

For instance, say I created a React Native project with 
```
react-native init MyAwesomeProject
```

Then I could install the generator with `npm install -g yo generator-rn-toolbox`.

If I now run `yo --help`, I can now see the newly installed generator and all its sub-generators:
```
Available Generators:

  rn-toolbox
    assets
    base
    bitrise
    eslint
    fastlane
    jest
    upgrade
```

Then I could want to setup few basic pages with a router. 
I would thus follow the [Base project setup doc](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/base/README.md) and run `yo rn-toolbox:base`.

Then I could want to setup a linter and run `yo rn-toolbox:eslint`, and so on...

Is it now clear for you and if so, do you know how I could improve my PR #34 to make our README clear to everyone?

Thanks! 😄

**Comment by yleflour** [comment]
Closing the PR due to #34 merge. Reopen if the instruction are still unclear.
