### ISSUE TITLE
[CircleCI] No generator named circle installed

### ISSUE THREAD

**Issue by guitoof** [bamlab/generator-rn-toolbox#56]
Hi everyone,

When running the `yo rn-toolbox:circle` as described in the doc I get the following error:
```
You don’t seem to have a generator with the name “rn-toolbox:circle” installed.
``` 

My first guess is that it is linked to [this commit](https://github.com/bamlab/generator-rn-toolbox/commit/465b60f4d307f58993cebafe7c073b5bc93590c1).
I don't have time to investigate more right now

**Comment by Almouro** [comment]
Hi @guitoof, the docs [here](https://github.com/bamlab/generator-rn-toolbox/blob/master/generators/circleci/README.md) say to use `rn-toolbox:circleci` instead of circle.

Can you try again ? :)

**Comment by guitoof** [comment]
@Almouro yes the new version 1.9 was not published yet at the time I tried the circleci generator ;)
I published it since so it now works like a charm ;)
