### ISSUE TITLE
App Icon not displaying

### ISSUE THREAD

**Issue by ShailajaV** [bamlab/generator-rn-toolbox#79]
Hi,

I did the following steps to generate ICON.
1. npm install -g yo generator-rn-toolbox
2. myprjpath>yo rn-toolbox:assets --icon path\logo.png
? Name of your react-native project 'MyPrjName'.
Entered Y. And it completed successfully.
After that i started my project again but i did not see the icon.
Could you please help me did i miss anything.

**Comment by Almouro** [comment]
Hi @ShailajaV, thanks for posting an issue here! :)

Did you restart your project with a `react-native run-android` or `react-native run-ios`?

Otherwise, you did everything correctly :/

If that's the case, can you show me:
- the icon you used to generate the assets
- your logs when running the command

**Comment by ShailajaV** [comment]
Icon is:
![xxxhdpi](https://cloud.githubusercontent.com/assets/25256931/23815789/438fc3e4-05af-11e7-80ae-359bbce38307.png)

And android related logs are:
Wrote android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
Wrote android/app/src/main/res/mipmap-hdpi/ic_launcher.png
Wrote android/app/src/main/res/mipmap-mdpi/ic_launcher.png
Wrote android/app/src/main/res/mipmap-ldpi/ic_launcher.png
Wrote android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
Wrote android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

It is placing the icon inside these folders but not able to see when i start the app.

**Comment by Almouro** [comment]
Which OS are you running on?
If Windows, can you try with the newly released version of the generator?
Maybe the paths were not handled well.

You can update with:
```
npm install -g generator-rn-toolbox
yo rn-toolbox:assets --icon path\logo.png --projectName MyPrjName
react-native run-android
```

**Comment by ShailajaV** [comment]
I am working on Windows. And tried the above steps but still not working.

**Comment by Almouro** [comment]
Hi @ShailajaV, in [this issue](https://github.com/bamlab/generator-rn-toolbox/issues/77), you mentioned it's working fine now.
Does it mean your problem here was resolved? :)

**Comment by ShailajaV** [comment]
Yes.

**Comment by Almouro** [comment]
Great, thanks! Closing this then :)
