### ISSUE TITLE
rn-toolbox:fastlane-env accepts blank spaces to set Keystore password

### ISSUE THREAD

**Issue by tpucci** [bamlab/generator-rn-toolbox#88]
`rn-toolbox:fastlane-env` accepts blank spaces to set Keystore password which leads to set `GRADLE_KEYSTORE_PASSWORD`. Gradle can't build with password such as `Blank space` containing blanks.

**Comment by yleflour** [comment]
Whitespaces are now disallowed in the keystore password prompt ;)
