### ISSUE TITLE
[Fastlane] Display error upon bundler failure to run

### ISSUE THREAD

**Issue by FakeYou** [bamlab/generator-rn-toolbox#94]
In a fresh react-native v0.43 project I get the following error when running fastlane-setup

```bash
? Please confirm the project name gen
? Commit keystore files? No
identical fastlane/Appfile
identical fastlane/Fastfile
identical environment/index.js
identical Gemfile
identical android/app/src/main/res/values/strings.xml
 conflict .gitignore
? Overwrite .gitignore? overwrite this and all others
    force .gitignore
    force android/app/build.gradle
    force ios/gen.xcodeproj/project.pbxproj
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn bundle ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by yleflour** [comment]
Which OS and Node version are you using?
Do you have more data regarding the stasktrace?

**Comment by FakeYou** [comment]
I'm on MACos Sierra (v 10.12.4) and using node v7.7.2. 

I created a [repo](https://github.com/FakeYou/generator-rn-toolbox-bug) with my code but it's really nothing more than a fresh react-native project with this library added.

I tried get some more data out of the stacktrace using `node --inspect` but it didn't give my any more information.

**Comment by FakeYou** [comment]
Okay I need to read the docs better, turns out I was just missing [Bundler](http://bundler.io/). After installing the setup worked without any problems.

**Comment by yleflour** [comment]
Nice! Is there any way we could have made it clearer that you need to have bundler installed? Do you think we need to make it clear in the terminal?

Anyway, I'm opening a new issue to add error description when the generator fails to run a terminal command.

**Comment by FakeYou** [comment]
For me I read the requirements in the readme and saw ruby and thought, "check I got that" and didn't bother to read the rest. Maybe add a separate check for bundler with the install command `gem install bundler` to the requirements?

Other than that an error description or a check to see if bundler is installed would also be very helpful of course.

**Comment by yleflour** [comment]
#100

**Comment by yleflour** [comment]
#100

**Comment by yleflour** [comment]
Doubly fixed in latest version ;)
