### ISSUE TITLE
App Store screenshots

### ISSUE THREAD

**Issue by franciscocpg** [bamlab/generator-rn-toolbox#99]
Hi guys.
First of all, congratulations for this amazing generators.

Did you guys have any solution to generate app store screenshots for react native applications?
Fastlane has the native solutions for each OS
https://docs.fastlane.tools/getting-started/ios/screenshots/
https://docs.fastlane.tools/getting-started/android/screenshots/

But I am thinking some `react native` way, probably with `jest`?
How are you guys doing app store screenshots for react native applications at bam.tech?
Thanks

**Comment by yleflour** [comment]
Hello @franciscocpg,

We mostly do our screenshot by hand right now. As Jest does not use a real environment to run the tests (as Karma does for web based projects) but only a JS engine. Thus the app is not really rendered and you can't take screenshot.

One way to do it (but it can be time consuming) is to setup Callabash to navigate your app and take the screenshot. We did it once on one of our projects but you have to take into account time spent vs value.

**Comment by franciscocpg** [comment]
Hi @yleflour 
Thanks for sharing this :+1:
